- name: Provisioning Desafio 
  hosts: localhost
  become: yes

  tasks:
    
    - name: configure / Update packages
      apt:
        name: '*'
        state: latest

    - name: Updating localtime
      command: /bin/cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      tags: timezone

    - name: Install basic packages
      apt:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
        - python3
        - curl
        - python3-pip
        - bash-completion
        - htop
        - screen
        - tree
        - telnet 
        - wget 
        - sudo 
        - zip
        - python3-boto
        - lvm2
        - software-properties-common
        - ca-certificates
        - apt-transport-https
        - openjdk-8-jdk 
        - openjdk-8-jre

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
        
    - name: Add user Ubuntu docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: apt update
      apt: 
        name: '*'
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      
    - name: Criando diretório workspace
      file:
        path: /home/ubuntu/workspace
        state: directory
        mode: "a+rwx"

    - name: Download Metabase .Jar
      get_url:
        url: https://downloads.metabase.com/v0.35.3/metabase.jar
        dest: /home/ubuntu/workspace/desafio.jar
        mode: 'u+rx'

    - name: Copy Service
      copy:
        src: /tmp/Ansible/roles/IaaS/files/desafio.service
        dest: /etc/systemd/system/desafio.service
        owner: ubuntu
        group: ubuntu
        mode: 'a+rx'
        remote_src: yes
  
    - name: Reload deamon
      shell: |
        systemctl daemon-reload
        systemctl enable desafio.service

    - name: Status
      service:
        name: desafio.service
        state: started
        enabled: yes
