- name: Provisioning Kubernetes 
  hosts: localhost
  become: true

  tasks:
    
    - name: configure / Update packages
      apt:
        name: '*'
        state: latest

    - name: Updating localtime
      command: /bin/cp /usr/share/zoneinfo/America/Sao_Paulo /etc/localtime
      tags: timezone
      become: yes

    - name: Install basic packages
      apt:
        name: "{{ packages }}"
        state: present
      become: yes 
      vars:
        packages:
        - python3
        - curl
        - gcc
        - make
        - python3-pip
        - npm
        - bash-completion
        - htop
        - screen
        - tree
        - telnet 
        - wget 
        - sudo 
        - zip
        - bzip2
        - nodejs
        - python3-boto
        - lvm2
        - software-properties-common
        - ca-certificates
        - apt-transport-https
        - openjdk-8-jdk 
        - openjdk-8-jre

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    
    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    
    - name: Update apt and install docker-ce
      apt: update_cache=yes name=docker-ce state=latest
        
    - name: Add user Ubuntu docker group
      become: yes
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: apt update
      become: yes
      apt: 
        name: '*'
        state: latest

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
      become: yes

    - name: Set JAVA_HOME
      shell: sudo echo "export JAVA_HOME=/usr/lib/jvm/java-8-oracle" >> ~/.bashrc    

    - name: Download Metabase .Jar
      get_url:
        url: https://downloads.metabase.com/v0.35.3/metabase.jar
        dest: /home/ubuntu/workspace/desafio.jar
        mode: 0644

    - name: Copy Service
      copy:
      become: yes
        src: Ansible/roles/IaaS/files/desafio.service
        dest: /etc/systemd/system/desafio.service
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Copy Script
      copy:
      become: yes
        src: Ansible/roles/IaaS/files/desafio.sh
        dest: /home/ubuntu/workspace/desafio.sh
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Start service
      service:
        name: daemon
        state: reload
        enabled: yes
      become: yes

    - name: Start service
      service:
        name: desafio.service
        state: started
        enabled: yes
      become: yes
    
    - name: Status
      service:
        name: desafio.service
        state: started
        enabled: yes
      become: yes
